### ISSUE TITLE
Debugging tools

### ISSUE THREAD

**Issue by sant0s12** [sant0s12/traffic-simulation#10]
There is a thing I wrote in main that lets you select a car and mess with it. It would be nice to be able to change more things about the driver (like it's parameters or current speed).

**Comment by sant0s12** [comment]
Idk if this is a good idea anymore

**Comment by sant0s12** [comment]
Yeah we need something to find peaks in acceleration and things like that to know what causes the glitching

**Comment by vvitez** [comment]
very funny
