### ISSUE TITLE
Oh yeah and the lane changing is kinda wonk

### ISSUE THREAD

**Issue by sant0s12** [sant0s12/traffic-simulation#11]
Title says it all, lane changing is hella wonk. I mean, it's better but the `delta` parameter should be stored in the `ModelParams` instead of being hard-coded. And cars still behave weirdly when changing lanes.

**Comment by sant0s12** [comment]
Is this resolved by #17?

**Comment by vvitez** [comment]
ye it was, anyways, should work if u do the pull request merge thing
maybe we need the hotfix the guy used in mobil to get rid of one other wonkfactor but should be fine now
