### ISSUE TITLE
Plot more than one lane

### ISSUE THREAD

**Issue by sant0s12** [sant0s12/traffic-simulation#35]
I still don't really know how to do this, but it would be nice to have one of those "dot graphs" but for more than one lane. It would probably make sense to make a 3D graph.

**Comment by NatalieSuter** [comment]
<img width="414" alt="Screenshot 2020-12-03 at 22 48 29" src="https://user-images.githubusercontent.com/74461941/101092284-b792b880-35b9-11eb-8d0c-801a2b7af8d9.png">

**Comment by NatalieSuter** [comment]
:)

**Comment by vvitez** [comment]
resolved, bois and gals, and printers
